ingress:
  enabled: true
  host: registry.sinanmohd.com

harbor:
  externalURL: https://registry.sinanmohd.com
  database:
    maxOpenConns: 10
    maxIdleConns: 5
  persistence:
    imageChartStorage:
      s3:
        regionendpoint: https://s3.sinanmohd.com
        secure: true
