harbor:
    persistence:
        imageChartStorage:
            s3:
                accesskey: ENC[AES256_GCM,data:sZ4L+sOrfolSkNojr1+LO/5RGKqM,iv:wBhDMiwag3Qhv6Tf9TFzE8EPcgHqfoDTUg9/YaJrpd0=,tag:1l4h+WR3vpiutwVM+I5Ucw==,type:str]
                secretkey: ENC[AES256_GCM,data:qK4HxGkoGytxO7SN6K4H9NS5/Dle,iv:sw1TalHLAu5dKqhXZqe3Ati1Ub5PQULNi0FcAvp2w7I=,tag:W8cWDoSMvwwovtxDjYVROA==,type:str]
    harborAdminPassword: ENC[AES256_GCM,data:pT2bNOLH1as9xlv6oLExZX5LcBQHmGdZDf8iLInPHCY=,iv:OAooW0+7MO0PLTvlu3Obt2qJxwAOKHGuo9gc4FgqzSc=,tag:uc40KXiQRJi78JQZR6xohQ==,type:str]
    database:
        external:
            password: ENC[AES256_GCM,data:iY1vTxw8hNI0yzYnAQ6cu6222ULsxLhiSsE=,iv:7GxwJa28fHze5nZmE5z4kcy7JiEAJeZnElWdYbdhhzg=,tag:QJzmR5xahx3vOqgM2DCm1Q==,type:str]
    redis:
        external:
            password: ENC[AES256_GCM,data:ivTyVqvVOGHo6Mrf7nrgkqh16Q0kz/P2vUypl5i1Qds=,iv:3/H0cbvCig57wixM60hmucMeHxSEM9RQ9soxGUqIJGE=,tag:oTv9Rzr1owqMCnVtszU0tA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV2JZQk1KT2dDVlpKRGdH
            VzZXbG1Xb2dJcndwRFNhNjhHUG9sbUNiaFZzClFTUFVSdlp5VXpjbzJ0aWNGVGxI
            YjFOK1JhSWY5SU9MbHl1ejI2SXU5NTAKLS0tIG5BWkVYdVUrRkdSaU9ucHBPdVNm
            MXZZTjdkcVc1WnJJaWJ5QVZiclROSG8Kx4YOumTdqtcs2LV/iFojvCWnAvTKrdCe
            /EvqTNlJi4bcl1vtFLkmeNiFDOC/jGRGnwH8Imse7TSel/xvCqpYeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMWN1NjRHZlk5aGJLM1Bo
            UHlhNkpZY044TSt6Z1ZKK21KdmZWLzVqU0ZJCjN5KzhGVmN4UWFrRFNTby9WaHpN
            R3RlckRsY0MrQW9LdTJRWmtGVzBZMlEKLS0tIDVsS3YvNDhOamMvdnhFakhnbDVq
            RWYyZzN5bEdBSjRaVlYxMFhpTFJqbWsK/PfMAp03IJjoAgJuns2WQF0DNVyrBny1
            0lurNEMu8sQYhO++cIF1iFOz4x203+vsd28LTjVPzu1YhASeEOFOzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rd62gt00vmx5cxq9q3gkc7h0qk3ujzx955u8hyrg3cevnmkm9q3suy32rx
    lastmodified: "2026-05-27T08:33:26Z"
    mac: ENC[AES256_GCM,data:ui8kXPYYHlGghVv/XeppjrTQNHOFnM3qkrLSynAreKt5bUtETMvz5pWl7x08wa6xieqBsiCAH9YOdj5aqNaJmg9TmOsHvMroZg0z4E258xTgtR1/PlJS5gvhBO1WUPtPQddSfLPWzNXCmhyTdvHeKbsrVNydtR8u47NRoWIhZo8=,iv:cC4PjZCfU5r4PHC4zFKhkggLc5q8SgYRZMUiZNw3BCY=,tag:s8hyPE6L8ACEtxjRmoI+ew==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
