version = "0.1"

[env.ha]
release_name = "valkey"
namespace = "valkey"
dependencies = [ "openebs" ]

[env.minimal]
release_name = "valkey"
namespace = "valkey"
value_paths = [ "values.minimal.yaml" ]
dependencies = [ "openebs" ]

[env.bud]
release_name = "valkey"
namespace = "valkey"
sops_value_paths = [ "values.enc.yaml" ]
dependencies = [ "openebs" ]
