passwords:
    harbor: ENC[AES256_GCM,data:uL2lpmagdiUoPQXBv516T8ZqF1U6yKOmd5gpfsYh0lk=,iv:W+UOk2HFA0YLMiJ+PFhR1TLCPQSq9pgniIRSVQqvIz8=,tag:wEVErG1Wt99UsvSTEA1PuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbm5nT0J2T1ZTcXBtYXBN
            aTVjcmNpVWFKTEJnUTNlSnJ1cmh1dzAza1E4CjZ4dGZSaUNrZmRjYWFmNDJkM2dr
            VW1DYzhzMTNNZ1ZoRG5DQ3FXRE90YncKLS0tIGtkSTdwNGdQQkdSK0RhdHM2Tklj
            QitwWWNDem9hTDVOYnRZaXNhMjdnMnMKs79o04p/iuAcQMxkDG17RXXwjw3yZnno
            2pK8nSqvUHuCGVPUXH7xU9/5jci+CpT8CobDUVclEtN9wF4sVWWvJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MUlKbkNHUHJicGoxRUdX
            ZlhQcGsxLzg3b0N0VjJvNmdPdFpEOWJ0bkdzCnBpUDN4bk54UlJOeDl5MitCc3hp
            T2cxamh5cnNvYTQxMXVGL0lkRkYxZlkKLS0tICtoWFJOWnhUMHluSDJZSnhoaURI
            S0JUaUxGSzlxalRTZXRmcFJZamxCNkkKdMtAnjh9Bq7G2Jy/nhi19R5V0mIDWeQX
            LWvulc1MBxR9nMim5FAPH6M54APxCBUeNn0wl20dVYzgXJJHBYoI0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rd62gt00vmx5cxq9q3gkc7h0qk3ujzx955u8hyrg3cevnmkm9q3suy32rx
    lastmodified: "2026-05-28T14:27:43Z"
    mac: ENC[AES256_GCM,data:nQyUxrCR6jpc+SyLpR1IFVohfSYtp/rwFd85rpBLTRcLFpLdQQPBkz0hWbqku2EjfU3j8B2DZgNmuCkMQvbyJVMn3MrMdgOp3++md7qJgKwmaRlo14+jCmQ2abTYex0d8wmK6bxEaoQ17yaM4DrJ1wJZjPlGSELldT7du6uD82w=,iv:+JOUkkCBzjx09vOZSzoSKHZr/GyvY1E1BYdWCgLqUXk=,tag:fQMzqgdtBP1sW9qOyeMWNg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
