valkey:
    auth:
        password: ENC[AES256_GCM,data:0rjYK8BM24Kb+638UrYH2jX3kjcOssgPC1P+nThg5j8=,iv:oXBkSi+6jFJVzEJh4klmu/xcsNeIo2sHrGv9K5ACtzU=,tag:cAPHU2i4YDYYKlGVux/sJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRVd6bE95TmVGZVIvcjRr
            OHA2VnRiNjJlZGo5c0tvUGpKZ0VaUGZYUlNnCjFLdEliVkRsY0tqMVlSQkZOSGZl
            SWhhd1lNZE45RUpOdGMyVHFDZGhVYk0KLS0tIDJzQ0R4MjZvNjhmdmRtRGxEUDVk
            TEo4VkdMMXNKZXFwclVYSEQxM3dmVU0KiOXSIPC379kcMPM79VUvEwR+uFMPZGaB
            KJX/KpZv9TpPYDs5D1L5T4dXdSfg4O3r5JIQrJK0uLXsf0Y1Zcs5NQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdjdRNWZoVzhDUjRYM09u
            R2J3NGF3Qk1yMk4wSS9WNjg4Y0FaVTJ4dzE0CnVNbXZHWG1IUnpPRS9UQW9xQysx
            dmNSR25uZXJjektMSVcrOFZSZG9Vb2MKLS0tIFE5eHF3cWQwREtTUVF0QzVMNFlF
            VlhDRDRlMVA4RzNZL3BHTDcwdWF1R3cKoyaAr5p+3hLNlRkr5LWk49T3vT5V0LK6
            YgRUzyly/JaGVcu+zv3lIoYNMQT6eQ5Hh5K4WQjVtrLqgBUVOe+UjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rd62gt00vmx5cxq9q3gkc7h0qk3ujzx955u8hyrg3cevnmkm9q3suy32rx
    lastmodified: "2026-05-26T12:59:55Z"
    mac: ENC[AES256_GCM,data:sZLPnfNkEkLev6frHOvhcTViG33FKs0VeJ7URh94CkA3G5MqqrEn0QTOty5JjTj2/tKXFC3CjR13II9mm1+1Z19q6GanAyidtGjXbYO3WpYBrPu6VhOCToiq+9zDNyJpog9Z0UPpHhaoqREy/y9DeDhFapUtSQkls4u4aHJwyM4=,iv:Epe5HBn9FCVZludWr/YiozVIo9WAPL78O5IyEyUqe9w=,tag:RV4L/ISXGubetxoMiMtvxA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
