harbor:
    persistence:
        imageChartStorage:
            s3:
                accesskey: ENC[AES256_GCM,data:qXna6ON9QmSxxEQHKfxX7dj07PE=,iv:XSkZ9pMwV1LUKdpWbcgpFGjOCOgUiJcSppNuV5A+KGs=,tag:1BP9ho+tzeH1dCY47W582w==,type:str]
                secretkey: ENC[AES256_GCM,data:W4NceBhlPRQwtjEKYXttd3IUCiYPAjwLCY0PdU8I6wOH5l31yzqCOtup,iv:FkF6bSPIGJIajIiOdxZa/nK3B96fJCn224nOdQE6hog=,tag:LGqCj+Vh4evNedbLv7fEIA==,type:str]
    harborAdminPassword: ENC[AES256_GCM,data:/vRVcatP0cpjY8ZsiDqd7YSXyfY7Cx6NDjXJ71PTa40=,iv:6n4aB8nbKvBusPncFLIVFwwgppeIgzrOC5ci5vdOhDk=,tag:4YkE4y2zRbCFFOgtXO9WFQ==,type:str]
    database:
        external:
            password: ENC[AES256_GCM,data:UnE9NMiivatuQxT4KFvSTi2flgEUQ95JAFC6CNczB5U=,iv:TBhBYCuCqwh5bvMt0IIa66Fvp2ojME/dgdwhcFVlAfk=,tag:RSgmJPbT8Q8kQk4+P4+cLg==,type:str]
    redis:
        external:
            password: ENC[AES256_GCM,data:vz6vdLt5KPaGbfmuRPKWQ3BFw8A49vPvXvMV2QiWGpA=,iv:7AC17EENlOfMEaDM9j8xSteSEqfa8m9BEuU38V6a3D4=,tag:0YRB061u9MfikN/eBmG2dg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV2JZQk1KT2dDVlpKRGdH
            VzZXbG1Xb2dJcndwRFNhNjhHUG9sbUNiaFZzClFTUFVSdlp5VXpjbzJ0aWNGVGxI
            YjFOK1JhSWY5SU9MbHl1ejI2SXU5NTAKLS0tIG5BWkVYdVUrRkdSaU9ucHBPdVNm
            MXZZTjdkcVc1WnJJaWJ5QVZiclROSG8Kx4YOumTdqtcs2LV/iFojvCWnAvTKrdCe
            /EvqTNlJi4bcl1vtFLkmeNiFDOC/jGRGnwH8Imse7TSel/xvCqpYeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMWN1NjRHZlk5aGJLM1Bo
            UHlhNkpZY044TSt6Z1ZKK21KdmZWLzVqU0ZJCjN5KzhGVmN4UWFrRFNTby9WaHpN
            R3RlckRsY0MrQW9LdTJRWmtGVzBZMlEKLS0tIDVsS3YvNDhOamMvdnhFakhnbDVq
            RWYyZzN5bEdBSjRaVlYxMFhpTFJqbWsK/PfMAp03IJjoAgJuns2WQF0DNVyrBny1
            0lurNEMu8sQYhO++cIF1iFOz4x203+vsd28LTjVPzu1YhASeEOFOzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rd62gt00vmx5cxq9q3gkc7h0qk3ujzx955u8hyrg3cevnmkm9q3suy32rx
    lastmodified: "2026-05-28T14:43:08Z"
    mac: ENC[AES256_GCM,data:gyN5Z9fixk3xhmqHF1w0ITeFUrclp88Ylr6mgPfy06NYHjSlo9JtS1lGrNhvllvsUObQRx6PRHXhyfrz3ybXe8HSBp025x/MEiFFE1OeD4E00K0TMNjOAPJfzYsDc1a5reu8+MzTetV3w2qcv6495uqqXNMuwMi6Pcpw+7+SZ7E=,iv:soCt1vq2h6d2avBJ2YTifvCg3M+by6PYaNZSvOGANhk=,tag:KILIbMbdwCFMlq092KB0bg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
