password: ENC[AES256_GCM,data:GdBOQaDCa2T72d550sI0IvoJ5usHz5y+zSnNm8ifKAI=,iv:58+YnpMN+f/JzGRwSZG/BRiU//CszplRNTnOGffQ84E=,tag:k9HT9KO0b7PJsoFytvxXKA==,type:str]
postgres:
    password: ENC[AES256_GCM,data:OEoyYgzeh/mH1JN0LULyZO96SLHLgrc3QmV/pys7hkc=,iv:kzm1jd0+YtUvCcX4xz+AAj72za4L/nKS6E/pugy3Du0=,tag:Y5QO0TjbAd/lQM30E1nhQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4S3BWMHZGVE5YM2FHSkQ5
            Sm40eTl5N1NDMVcyOHBoN1ZJUHlGNHJ4d0NNClo2VWxGdGxSejJPNGhGbG1XZWRu
            ZklvcDJuTkIwcmlXcE1jSlFlTGw3UWMKLS0tIGtqWG5LK0FjZ1hrelVHdGNSeVB5
            ZW43d0lVOVQxVUQwZG9GdjRObGtDaGsKAuDmERg3cf8ucAoz0tNcO53lzQGPMZkR
            DUoJ9tJH/oxmBOLJ7FvYgzuonBsv73+O2iif8EUDLJY3jO4NDGTmtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRU3pzYUQ1RW40Tjh4WWcw
            R1ZqdDZySFgrY1VpNXBWZTA2aXpYS1ROeGxvCmVyRjcwVG5MckRXSVpYQjMydklW
            dXVLN1dLeE1yWkQzdWVrZUhnbnhqc1EKLS0tIGRjY1E1NzlKcmlKZHRCWWRHVk83
            K2JxV1M1Y1p0dHg1b3RmdzV1Tmh3dzQKvhtKoZlBWu88AFRpamnbC12Z1CEOYxWo
            ULBLXkMZhaSt0po4x6ka4VbVHhTC++Uxu9xvHXpWknsqa+mY84/JYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rd62gt00vmx5cxq9q3gkc7h0qk3ujzx955u8hyrg3cevnmkm9q3suy32rx
    lastmodified: "2026-05-27T09:22:16Z"
    mac: ENC[AES256_GCM,data:DhcSw1uz7q6iAIYhw7xsLb7Fu2jfHTJhx9sMripdhncpUixSahK5oRjaS7vdtO6ngavwSTDtYgsRX68k8AcL7z+y8AThqXiktX7SZ7hlIOiB37MbBnUdGuxbS6MA6kL/nsy5O6pKWMrFGw0eSt9Zyvcf5xKQnSskmABAL/RzaC4=,iv:GwaXb4UohfaCwwIE7jTp6WRQ5U+o8hyoZArQCPtHrJA=,tag:R0Fu0oiPsQcE6mscIhfMtQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
