users:
    monitoring:
        password: ENC[AES256_GCM,data:0Ij543lLipZivzfaca3b7nYtzdxK2IkeM5pY3LSRokA=,iv:VFRP93jZqu35FtRlY2hmGDpi2nJSfcz3w5JbV6N1bj0=,tag:3Zv4MDOWAGJJVE2uHAph8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadlJna1pTeXJ1RUtsNlh3
            cmhsakZUQml2KzhpUWxxTy9Ta1B5bHNRdVNjCi9UWXNJalcvWnB3L3JwN0JmZGg4
            eDhZOGluMXdsR1p1dXRWam8yUEltbm8KLS0tIDdPQXpVZXdzUWRvMHRoRFFWeVk4
            SkhMNTArY0VLSy84WXJUMWNoNnV3UmMKqwyibbeZtc2JxM9sZp7IC/RtBp3OslQ/
            UBquR5jIf8Jl1WXM/xFDItSkKKdFIb2v1UQ+YGt/25dC/jFa+bftwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNnpZQjBSZW9nOENNRXdh
            bTM0MWtEYlhtZzU0S3M5cW9mQXFuMnNNM0gwCkEwS3A2WEIvdlYyVFdDQWw4MzZl
            ODYrZDJXMTl3UkF6ekNnejNSVEhSUFEKLS0tIDdPd1FaOVo2TzlPdXR2aTh4QTJ0
            NHZJM2c4bkhnRlF0dC9zREdRYVBkb1EKQpJYKbbiDcMJhprAEI6Nd5MNtDIkTw24
            Hw0M71i/xDDRsI/3zT06ccCWmpVLjO5wPbk7jo/Og24c9gL5pC3Z+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rd62gt00vmx5cxq9q3gkc7h0qk3ujzx955u8hyrg3cevnmkm9q3suy32rx
    lastmodified: "2026-05-27T08:27:42Z"
    mac: ENC[AES256_GCM,data:i7yODZdQ9fhTKLKx6QtpaIOWIYDIwJ4KRy6l11j485gsysHNHiiLqWbwbXLP3UozX4QKNLywj+MuAQHq4rlIWRrLPxIsmDEPz6dSZ5V5nBot7L+o5Ss1hW0kneghlYeG2LCLurLDpjV8JPYdUhpRmVURr8rEwK5DKja7vBXMVE4=,iv:lmzHgYl0gRvGFotOcO7GpfqS+NR1Ypj+roEeANFM3vw=,tag:xqwuiykb9MEYFGTJ0On5LQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
