monitoring:
    valkey:
        password: ENC[AES256_GCM,data:Ygv/NvZJcKRVVzFpAeV40Zm/3jd7ZmMxwaXL4dkYUtA=,iv:4Bd5/XWFLgk6BAT869a8qOG3S1x86MULxqHOUT5dugE=,tag:PhJyabZdGPQYdaEXx50hig==,type:str]
    postgres:
        username: ENC[AES256_GCM,data:ttIyot4V91rYZA==,iv:LQAGs5HUc6rh2JlFTIcewYD/bWt0QlS0w95DANVT9nQ=,tag:seP8vNAGdJJZZiSyHIdX6g==,type:str]
        password: ENC[AES256_GCM,data:5/YgYIY7qDtPf6urWIhz8wpQHVEF1eEVMezP7FzIG9o=,iv:empSouFC/tw56yd6YaqegCwyGq61K+GG0RrJUOV46j4=,tag:ntNuy3fgSnjjF+ytQ7Ygxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dnVlV3dpcnJoWGtOdHcr
            Nms0K3hwdmVyMTJoT2ZwdEJOQ1Z3bzZaWlJVCkdsTk5NQ05IOGwyaTNXTW1HbmxC
            WWFpRXFGbm1JaDQ5ckFoQkd5dzN3SEEKLS0tIFU5RTdxalZyTDc2TWoxZ04zUmVz
            THNPNVV3U2dPTFlBOFBaSU5yck13N2sKwyWQd8csm77xBsv43yKrxu+JaEYqmxDc
            bVBLFh2li3KFdxnXdWNz456E+y3mYZ1ZPLOV3ne833/sCiUZz6rHxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZXdBZjl6ZVArMC85NUVT
            N0ZTQThSWWxyYUIrdG51SzdURG9UTHhQcERJClFBQTA3Sk5nRzk3QUYyZ28yaWVO
            WjFuSEcxOWFqT0oyd2xJdjNRdC96NE0KLS0tIC9ZSTc3T1FyY0lRTGhFZThDbzhI
            WkFBR09hTkpYMk5rZFhmWWhYOGFYZWsKGNcdpt7P2spQbJVIDgVzg1hsNIYVlMpd
            R3T3xmgpkjepr5e2m5xCSFwtuofNjHXu0YBRn8vkUE1sYECtpqHZnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rd62gt00vmx5cxq9q3gkc7h0qk3ujzx955u8hyrg3cevnmkm9q3suy32rx
    lastmodified: "2026-05-27T10:15:06Z"
    mac: ENC[AES256_GCM,data:VmzFK1yFp1hGcXfeIp/NCfrC7hO+q59pXFPzvNJTsmBaPkILxPgdLYa1D8YIN6Xp+s76jRfOAeAcUWzuWF8aWQ4yI/yGzElapH3IFZE+D2kixbev/DVedwVWIVf/L0i2E51Wj6o/hpx0ev6sqrOUWw2h+2GElloVbG5pN56Rdf4=,iv:De9QQIPSatHY6QQxZ6ldJq3cw2VNlBIgXFfVHnLiVP0=,tag:xWa+tDNr5t9dj0io6gBOew==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
