monitoring:
    postgres:
        username: ENC[AES256_GCM,data:ttIyot4V91rYZA==,iv:LQAGs5HUc6rh2JlFTIcewYD/bWt0QlS0w95DANVT9nQ=,tag:seP8vNAGdJJZZiSyHIdX6g==,type:str]
        password: ENC[AES256_GCM,data:5/YgYIY7qDtPf6urWIhz8wpQHVEF1eEVMezP7FzIG9o=,iv:empSouFC/tw56yd6YaqegCwyGq61K+GG0RrJUOV46j4=,tag:ntNuy3fgSnjjF+ytQ7Ygxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dnVlV3dpcnJoWGtOdHcr
            Nms0K3hwdmVyMTJoT2ZwdEJOQ1Z3bzZaWlJVCkdsTk5NQ05IOGwyaTNXTW1HbmxC
            WWFpRXFGbm1JaDQ5ckFoQkd5dzN3SEEKLS0tIFU5RTdxalZyTDc2TWoxZ04zUmVz
            THNPNVV3U2dPTFlBOFBaSU5yck13N2sKwyWQd8csm77xBsv43yKrxu+JaEYqmxDc
            bVBLFh2li3KFdxnXdWNz456E+y3mYZ1ZPLOV3ne833/sCiUZz6rHxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZXdBZjl6ZVArMC85NUVT
            N0ZTQThSWWxyYUIrdG51SzdURG9UTHhQcERJClFBQTA3Sk5nRzk3QUYyZ28yaWVO
            WjFuSEcxOWFqT0oyd2xJdjNRdC96NE0KLS0tIC9ZSTc3T1FyY0lRTGhFZThDbzhI
            WkFBR09hTkpYMk5rZFhmWWhYOGFYZWsKGNcdpt7P2spQbJVIDgVzg1hsNIYVlMpd
            R3T3xmgpkjepr5e2m5xCSFwtuofNjHXu0YBRn8vkUE1sYECtpqHZnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rd62gt00vmx5cxq9q3gkc7h0qk3ujzx955u8hyrg3cevnmkm9q3suy32rx
    lastmodified: "2026-05-28T14:40:52Z"
    mac: ENC[AES256_GCM,data:7VMLFS39ZS6C9rOqdPIE0/xS3Dg0BzVQkXEfmXbvwjF+mJAYYAWhJ98Ihmjof4JmNG8sVlX1ztkOXSmHWLB3ImpBPkfu8kdUPLiv75Wj+RCCXusDXO7uxaUDM40VOVbpn20KpFP7/3MZ29+CdHKOd2KyXwh+1p3t63HBJ08cQ+k=,iv:pI34lQG4M4P9LeMGl845gBLRLET+DT0ZZegBOOWqsgw=,tag:rXJafH2mWaDpv0Z0lAhREQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
