postgres:
    password: ENC[AES256_GCM,data:n44kESyyysQeCNwyQbiRMs++vqRcRuiHAZADS2VHDqc=,iv:tO01xFbIQRz8ghd6S48wlICsILjE577y3XcbLS2OazY=,tag:WeZk23mvGipcexwLY2J+NQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUHhaRDNVeElncjRKZE5l
            RXhvS2VLZlpBRFdJUGh6ZVJhSWRneXBrRzAwCm8xSmFYVUdmRU9vUUtBdmh4cTZE
            M1I3UERvVGg2NHIyRnhSWnZZRmtxUXcKLS0tIGJXK3hTT1cyUktpWUN0NkpSbUkz
            OFYwbmdxOFlpOWxubE1BYy9hWU9XcW8KRtD9VI4rylBX94O9LrsL31xeCaVAJ1mL
            FgmknXhCQtxsgTe6Ov6Tx7IF7DK4yofDLyJSJxLEkW3Y2NxMNLYLsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbzFjR0ZRZ0tRYW5aM0Yv
            OWkwVU96c01xeG1jZHhZcWVua1kwM1pMUm5RCkx5bDZhSy9jTVVra1IyOXpFRzho
            RUpua2dGQUthUmlmTm1zNnhhL0pjVW8KLS0tIGxwb2JvWGptZm5tSGw4QXNMbksv
            KzV0dUcvLy91d05uTENzUHVYODhjdWcKDGr+pF5ZJutlgyO9CCeAhrVhtHb/cJPP
            JaVmqLlTn1ri9AOgRnUMYgk7xXDgZ7I3tOWSy6JTiKS3Y7L71yxkuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rd62gt00vmx5cxq9q3gkc7h0qk3ujzx955u8hyrg3cevnmkm9q3suy32rx
    lastmodified: "2026-05-27T08:04:26Z"
    mac: ENC[AES256_GCM,data:qroDugi1kOvZ+B6H139omtHJH6QATYcI2xGiCbc+4lutEaTKsyWsAT7RWlv0+zvskkejWxc5hMDMs00RQiCJNxDb9beLu5bt6SH8FKcX3Dfk2bqzdOUV4H9osLH5UO2C4PaGn/UwE1EDGlHL+oh/lKVOA/mgPigNtSqdL9y6Lys=,iv:uBL1Z7A+//Od7MMo7u7v/qdjFImdlI3E2G/B3YzY45s=,tag:A+7CLsUVGIzLJBWGZziJwA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
