ingress:
  enabled: false
  host: s3.sinanmohd.com

volumeSizeLimitMB: 5000
defaultReplication: "000"

buckets:
  opentofu:
    reclaimPolicy: Retain
    versioning: "Off"
    objectLock: false
    anonymousRead: false
    quota:
      size: 128Mi
      enforce: true
    access:
      - user: opentofu
        actions: [Read, Write, List]
  harbor:
    reclaimPolicy: Retain
    versioning: "Off"
    objectLock: false
    anonymousRead: false
    quota:
      size: 16Gi
      enforce: true
    access:
      - user: harbor
        actions: [Read, Write, List]
