users:
    signoz:
        password: ENC[AES256_GCM,data:Fn3ZX3VoPWPI/pOes82uUezUrmjG48vLQCvjqYH/ioM=,iv:Zothzq35P++qr3VlIp1/kaWjzZHdhGrtyzs3My7tMYw=,tag:z/nTF8kgtL6q8mhkE2xnZw==,type:str]
    monitoring:
        password: ENC[AES256_GCM,data:eiKjNBmL6zyJ6TCle9jJm9e1DVQ08uMfAuZxAUD4r1Y=,iv:QhcgK4nZ2ig2H2E7/5P48xrUNpbbqw3r8h457CKMnqA=,tag:qMhccKke5Bdz6BPWlyIH3A==,type:str]
    keycloak:
        password: ENC[AES256_GCM,data:e2Shlm+M84u9VrY7O9VJd3WPaTbuKJCYWyvO0lusl8g=,iv:0jn/9auiuaOboO8zS9gxQiP8/7/fVubMpzBy6OJEAI0=,tag:l6Mk8SmcteApKYNCwXuEMA==,type:str]
    seaweedfs:
        password: ENC[AES256_GCM,data:ftiCaAigE5xAUoqwq4A70JA6Gre4A03gEUCOorcB5Zo=,iv:99TcPXEQ2EoDuQJfJZ13rWT2I52eRu2Vlgux+zOH+Gw=,tag:AWs4Y5mNl7gBf2LuI67BaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NkkzRENCRlRIbUp4N3M0
            Y24yeDNrbHljRmN5TzJsMUtIWmo4V3ZGREhrCnA3WHBrTFNGRGVyS0dKeUt4YkVF
            WWNtWGovWEQrdjh2dDF6TW9JN0ZLUkkKLS0tIDYrSTRpZHhuVk5UM1BtTFVaRmlW
            dy8zYVJ6Wk1NakNQU2tFU1VnNHYwK1UKHQQui2Rpb4MLk97758LzEFQGKIyJuPug
            ochHzaHJeMcEn3SRd0WB0I70Dv3cS397qgoO2Y4GHR0cqRCTr2jzTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4RGlObUhDa3J0ejVzN05w
            OTh6ZmNwMyt2MjEyOTZUVVByYTdzWjcvVkJRCjhKNkt0K2VXemVETW1zdGlxRUhq
            c09ESi9NN0FhVXRxVkVWcFNjZ1lVcG8KLS0tIFdyM3hZYng5YnlBSGIvUGFyVzBZ
            aXhmdlhCT1J3Y1lLOWNrdTBmUkgydXcK8h7tSDwN/ppqCBwmjCUNBcjXoGdw3yge
            t5+bO3dtijsTJ2+PfOFDyMfpgG1ECdnfYqHlAs6Yy+uc2HrXHkZKmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rd62gt00vmx5cxq9q3gkc7h0qk3ujzx955u8hyrg3cevnmkm9q3suy32rx
    lastmodified: "2026-05-26T18:31:05Z"
    mac: ENC[AES256_GCM,data:vGmWz5OHLIpSSRh5HUu6GbauMUtgCUGQz2rVExLxenpkrnlBMnmLrvTCT20+wkA1Nv2bBSffPLipLRGH1F0qyBPqTfVqrUXMhPaL5fxW7RMkqatn52VDRQXbnQROu+im+neF51c+2QZVZop53Iiy2dVcUSHbeo23CoXMJyxKN2M=,iv:Yk5iNK13UZ+V+h4qtYOdJcU3EOYPRM530pMMuRV1u38=,tag:mY1SlLuQn0vcCFuC3sOZpw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
