sopsAgeKeys: ENC[AES256_GCM,data:jO81mYOHse+PNRz39ONPbrGUARgl4k3bQpg6DWkwfxDcMUBB8/AjgVlZLsdU7utkVsQd9TXZ9X4ioMg6OVzppv4rCcf1cV8sMQWmaxUtM5Uz4NVVYmNt8lzscwtDvjp0yGcxDQVcUByMkjoFcg3sgOMXHdE8beXdey8jg/i/AkMVdQY/C383nlgRMHcWY2O92T/ZYyJZ7W96fUyiAX74rBfxq7joma/1+HaZ34a+Hc9KA9kOm4z0DYbziq0=,iv:XUpMhYCnlqzAOwiVDnYyWKN4tqAXeFt5+aPYL3HLAZ4=,tag:1MJM5fCPFUYjN5gohT5xFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUzJ6MUx0MDlYK21SdXhY
            WTlJZnFmM2cwczNTU2dnTFhBcXhTUVllTm5BCmdLdnhORm5UaVAvT2NqRFF0QWtL
            TFlObWFzaTN2NjhSVzN1cHB3enRzOGsKLS0tIDJzMVFraTlONHAyTFpmSnkwNzNt
            dlI3UmlqeWg5KzE1OWw3UE1vUGxWekkKODX4jnJ83tl6g42n37q+KSJzdzg8nMVf
            jxEtdHyGgyQcFJih79h5zQeA0+3UlWEtKZID+gD2cnzkC0G82jeDEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaM0xzbTdTRWl1eWlNM3lp
            eVdUaU1xVEJjdXNvYUQzOTl1Tld3RHFGSTNzCjM4dFpJakpCenVOVmZOLy9UeVlu
            R2psajQwczdTeUN6L2RmWkJVNENuOVEKLS0tIDRwOFR5Yjd3MmZBeUs4RmhyTG1Q
            blY2RWdsNTBYcUV2UzFOdFlLVzhMakEKeVaxgNKxk1p0Q8QZg/q1wbruzsjA5h2W
            OtE1wHdREUUv5u3rwcQ+MGmVagqFv8nHd753Z5bzV4P3y6VEI7XjKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rd62gt00vmx5cxq9q3gkc7h0qk3ujzx955u8hyrg3cevnmkm9q3suy32rx
    lastmodified: "2026-05-26T08:45:32Z"
    mac: ENC[AES256_GCM,data:OVmW8Z9JvhZzHF08JQ6boVXFxlRg0S3YPDMrPWLAKVvJFs98oNUnA73G8bNq99ZeoL3Hj/Cd8tiNaJM+EXNoEsiB/lUO6Cz4iZLl2ufyulMA/qQLJWrA7KAMleCfI1oKzWaETGnZ8+fRThd2ZJvW92gIVe7v8q1MAhjD1ixRlIY=,iv:wjyZy/Fo7anL9VfYg07HyJilXJOTGpOZxa0bbPmTAPs=,tag:LYuiuEORmPUCjuDtq3LoPQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
