users:
    signoz:
        password: ENC[AES256_GCM,data:4fd1ZW6dacNa7sh0SjWzQSZTozwrcCo+b7tvRa3czRg=,iv:3WQh1r2ZnVUQjpdesbNnqsBJPMdGshIAe2pDWilNeCU=,tag:xc8Qyx04X/kOlR6MwXUBRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMGo2alJxWGFydU5tRW5U
            RVFpak5qbEFtaTI1SkdpWDJJVlJ4bkpUQVRVCjRuWUlPZWh0WU9hUm5hdnlJVkY4
            eW9veklSN1BTQUlTUXFqUko3REQ2TDAKLS0tIHYrSXlwdXJwYnVydEVEM0wwV09m
            YmlKbXpuMUNQLzdpVmw0bGZtZWNwZ28K3D1mTTsesARsO8hkkvPL5LP7dxlkx50i
            L/QZnygX6v5b7zmwM9MLeAzuJXGHW10AC6E9w7RjLRxq/gSHQ2i0ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bnJWMkg2WmZGTjF5VDRG
            RnlsZ0JoSE9YQTE3TUNLUkpYOVdkWm4vZUY0CldOWVdET3h2OGFoMDFWRHFlSXk2
            WHYrUkFqbUFyczFpVnlEdmZFeVJkOXcKLS0tIHk0SnZZV1J1UlJOKzhHR2FEUEt6
            cjRyclVsZ0lBbUFBRXBPQnFzWUZROUkKzEtwlq5BCQXQUAZFl29bzMFyAchxJnGF
            SEdwUsseZSxs2jX61c3SHjeQ45p0cqB9jcZyQcHUQvNXrf0QBvA7HA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rd62gt00vmx5cxq9q3gkc7h0qk3ujzx955u8hyrg3cevnmkm9q3suy32rx
    lastmodified: "2026-05-26T18:38:22Z"
    mac: ENC[AES256_GCM,data:/yQ/2Za5x0po0ysfml4K2o67TgsP2fLvpZinc7bXg+N9gcYfr3ILyKcH7xVnnzgAXZxA4hZGt3zoqbxniUffkzR6LBXEAkCPyKXAe8x2gQQIxJ/lMy3JCQezxG4xHABvS70KqUo0aFaKJ7K3OaZsfiuKgfbKUdA2+tmVoVa7PLI=,iv:lfM4pOCoreKSA8fSXxZ7dmOvhkwrDPBaM+5D+ptWx84=,tag:b5duMCZIpwVtpo6X3v++4A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
