apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: argocd
            namespace: argocd
            valueFiles:
              - "secrets://secrets.sinan.yaml"
          - name: dapr
            namespace: dapr-system
            valueFiles:
              - "values.sinan.yaml"
          - name: keel
            namespace: keel
            valueFiles: []
          - name: kafka
            namespace: kafka
            valueFiles:
              - "values.minimal.yaml"
          - name: mongodb
            namespace: mongodb
            valueFiles:
              - "values.minimal.yaml"
              - "values.sinan.yaml"
              - "secrets://secrets.sinan.yaml"
          - name: harbor
            namespace: harbor
            valueFiles:
              - "values.sinan.yaml"
              - "secrets://secrets.sinan.yaml"
          - name: cert-manager
            namespace: cert-manager
            valueFiles: []
          - name: clickhouse
            namespace: clickhouse
            valueFiles:
              - "values.minimal.yaml"
              - "values.sinan.yaml"
              - "secrets://secrets.sinan.yaml"
          - name: keycloak
            namespace: keycloak
            valueFiles:
              - "secrets://secrets.sinan.yaml"
              - "values.sinan.yaml"
          - name: openebs
            namespace: openebs
            valueFiles:
              - "values.minimal.yaml"
          - name: otel
            namespace: otel
            valueFiles:
              - "values.sinan.yaml"
              - "secrets://secrets.sinan.yaml"
          - name: postgres
            namespace: postgres
            valueFiles:
              - "values.minimal.yaml"
              - "values.sinan.yaml"
              - "secrets://secrets.sinan.yaml"
          - name: seaweedfs
            namespace: seaweedfs
            valueFiles:
              - "values.minimal.yaml"
              - "values.sinan.yaml"
              - "secrets://secrets.sinan.yaml"
          - name: signoz
            namespace: signoz
            valueFiles:
              - "values.sinan.yaml"
              - "secrets://secrets.sinan.yaml"
          - name: valkey
            namespace: valkey
            valueFiles: []
  template:
    metadata:
      name: "{{.name}}"
    spec:
      project: default

      source:
        repoURL: "https://github.com/sinanmohd/infra.git"
        targetRevision: fix/unused
        path: "charts/{{.name}}"

      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{.namespace}}"

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
  templatePatch: |
    spec:
      source:
        helm:
          valueFiles:
            - "values.yaml"
          {{- range $valueFile := .valueFiles }}
            - {{ $valueFile }}
          {{- end }}
