signoz:
    externalClickhouse:
        password: ENC[AES256_GCM,data:k/Gp1rTZDK/CxCNx0ipsRLizeVCXljwSS8YcGNO/t5A=,iv:pM10mBNGRkNE90eo0cgG3C9FUMGPLGHVQQwAqz1D7aA=,tag:+vP+up8H1EIUFUxZdzvEmA==,type:str]
    signoz:
        env:
            signoz_tokenizer_jwt_secret: ENC[AES256_GCM,data:iLQ1xrqvmfmtjqvGPSZWvwusKeRWhdmJNZOWOWJVZGI=,iv:AYfFKiQAlRXfSpW9JexYx02S/Xpx5R9TIPK5Knz66zs=,tag:BFh/J1MUJzeAT899+EIKNA==,type:str]
            signoz_sqlstore_postgres_dsn: ENC[AES256_GCM,data:AAmim5ZHAb4TrAuE7+Oh/juwJ2U8StrpumdDFeQfFhxb5nAqZgWZPU28mqt95qloXjS8HohpUD6eedR5R3mL10z7kF+NoyhxeiMAVz9iuxdETc6V4kW1VjBeUrlu8ipbcMCo,iv:kTdcDwxLr/2Wdlebd5Wc85Qki2BMZOEZik4mSv8OPTc=,tag:sZToPvm404VBbVRCx7+e4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWFVjTFFzN1pzak0vbkpN
            UXNDZ1NFZk04aHJhb1lybldMVTFkNmhlbG1vCjhKRC9Wc1U3VzJDVElVY3lRQVFv
            S2NpdHhUYllCTlM0cDliUTNJbHVJeVUKLS0tIHg5QVp0Qm1CQUhkVVlkem5DeDFw
            N1hCVnRpMmFLT3E2VkowVnZLRWFWMVEKv4r1fOOYteQXR7S9XqHrD25k60g/HL/8
            7+pNNiATfT4mAHrLER//jLv5MzDOQdX2cTcrUL2Vt+XdR4TDFMPcIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q5sfy74d53n6jxlgsc2zrsz4wcl9d830nxuagc3wfmdkrrp55ckq9ev6nv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZTA4K1lRMStqVldrbC9p
            VDZnaTVGcGh3djdEMG1BUjdlNUhWUTFBNEc0CmcybDZNSFp1djJ3cElCb3hjV0tL
            Ulh3bzNtSzFtVGYvTTNWMDJPR0cySkUKLS0tICtmd1Z1V3R3bjhvWGZGa3cvZDJW
            b3FjQzRiUGp2c1NzQS9YYnRONldua1EK3gRk++tQyTmlwfcwC06qjOABi/P90wQ5
            9C66Z6oIgQcSXHd0M1GkDDzvVtzJ3MwlJ9/mFrfIMCNcMVZDqrNI+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rd62gt00vmx5cxq9q3gkc7h0qk3ujzx955u8hyrg3cevnmkm9q3suy32rx
    lastmodified: "2026-05-27T07:58:26Z"
    mac: ENC[AES256_GCM,data:ENvf5Q4Cxq+ofb1mENKHHaLYX1kZxSk6NwwX50WgaHlRMzy5YF3r9tHMHXWpmkNu/6vnRJVX1QEKIe88S33+pWdFRLSANqqfEgWhbLEyLwwT6oDJqGSpbHNTWPSmSi5sxGwqkDG2IYhKftrI8xzWx1mExnvlTRBz0U8cleJXbMg=,iv:/aD+pC2eQ1XXgz54tkm1aQAQnxJ1/xD6QfmmW2Rg9vs=,tag:Dro/MIUrAklwNcNkNbWYgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
